//
// Copyright contributors to the IBM Verify Authentication SDK for iOS project
//


import Foundation
import Core

/// The authorization server issues an access token and optional refresh token.  In addition the ``TokenInfo`` provides the token type and other properties supporting the access token.
///
/// When retrieving the `TokenInfo` from a persisted state, ensure the [JSONDecoder.dateDecodingStrategy](https://developer.apple.com/documentation/foundation/jsondecoder/datedecodingstrategy) is assigned.
///
/// ```swift
/// let json = """
/// {
///   "tokenType": "Bearer",
///   "refreshToken": "h5j6i7k8",
///   "accessToken": "a1b2c3d4",
///   "expiresOn": "2022-12-30T11:30:31.340Z",
///   "expiresIn": 7200
/// }
///
/// let token = try decoder.decode(TokenInfo.self, from: json.data(using: .utf8)!)
///
/// // Print token
/// print(token)
/// ```
public struct TokenInfo: Codable, @unchecked Sendable {
    /// The access token generated by the authorization server.
    public let accessToken: String
    
    /// The refresh token, which can be used to obtain new access tokens using the same authorization grant.
    /// - Remark: The `refresh_token` is optional.
    public let refreshToken: String?
    
    /// The lifetime in seconds of the access token.
    ///
    /// For example, the value "3600" denotes that the access token will expire in one hour from the time the response was generated.
    public let expiresIn: Int
    
    /// Typically "Bearer" when present. Otherwise, another `tokenType` value that the Client has negotiated with the Authorization Server.
    public let tokenType: String
    
    /// The scope of the access token.
    ///
    /// If the scope the user granted is identical to the scope the app requested, this parameter is optional. If the granted scope is different from the requested scope, such as if the user modified the scope, then this parameter is required.
    /// - Remark: The `scope` is optional.
    public let scope: String?
    
    /// Additional data parameters returned from the token server.
    public let additionalData: [String: Any]
    
    /// The type of token that the authorization server will return which encodes the user’s authentication information.
    /// - Remark: The `id_token` is optional.
    public let idToken: String?
    
    /// Creates authorization header from token type and access token.  The authorization header is used in subsequent HTTP requests.
    /// - Returns: An authorization header.  For example: `Bearer ABC123`.
    public var authorizationHeader: String {
        return "\(tokenType.prefix(1).capitalized + tokenType.dropFirst()) \(accessToken)"
    }
    
    /// The date the access token expires.
    ///
    /// When the token is obtained from the authorization server, the `expiresOn` date is calculated from now plus the ```expiresIn``` value.
    ///
    /// The `expiresOn` is used for determining ```tokenExpired``` and ```shouldRefresh```.
    public let expiresOn: Date

    /// The flag to indicate if the access token has expired.
    public var tokenExpired: Bool {
        Date() > expiresOn
    }

    /// The flag to indicate if the access token should be refreshed.
    /// - Remark: `true` when 90% of the token lifetime has elapsed since the token created date, otherwise `false`.
    public var shouldRefresh: Bool {
        expiresOn.timeIntervalSinceNow < Double(expiresIn) * 0.1
    }
    
    // MARK: Internal Enum

    /// The root level JSON structure for decoding.
    private enum CodingKeys: String, CodingKey {
        case accessToken, access_token
        case refreshToken, refresh_token
        case idToken, id_token
        case expiresIn, expires_in
        case expiresOn = "expires_on"
        case tokenType = "token_type"
        case scope
        case addtionalParameters
    }
 
    /// Creates a new instance by decoding from the given decoder
    /// - Parameter decoder: The decoder to read data from.
    public init(from decoder: Decoder) throws {
        // OAuth keys
        let rootContainer = try decoder.container(keyedBy: CodingKeys.self)

        // Access token
        self.accessToken = try rootContainer.decode(String.self, forKeys: [.accessToken, .access_token])

        // Refresh token
        self.refreshToken = try rootContainer.decodeIfPresent(String.self, forKeys: [.refreshToken, .refresh_token])

        // Expires in
        self.expiresIn = try rootContainer.decode(Int.self, forKeys: [.expiresIn, .expires_in])

        // Expires On
        self.expiresOn = try Self.decodeExpiresOn(from: rootContainer, expiresIn: expiresIn)

        // Token type
        self.tokenType = try rootContainer.decodeIfPresent(String.self, forKey: .tokenType) ?? "Bearer"

        // Scopes
        self.scope = try rootContainer.decodeIfPresent(String.self, forKey: .scope)
        
        // ID Token
        self.idToken = try rootContainer.decodeIfPresent(String.self, forKeys: [.idToken, .id_token])

        // Additional data key
        let unknownContainer = try decoder.container(keyedBy: UnknownCodingKeys.self)
        self.additionalData = unknownContainer.decode(exclude: CodingKeys.self)
    }

    /// Encodes this value into the given encoder.
    /// - Parameter encoder: The encoder to write data to.
    public func encode(to encoder: Encoder) throws {
        // Additional parameters key
        var unknownContainer = encoder.container(keyedBy: UnknownCodingKeys.self)
        try unknownContainer.encode(withDictionary: additionalData)

        // OAuth keys
        var rootContainer = encoder.container(keyedBy: CodingKeys.self)
        try rootContainer.encode(accessToken, forKey: .accessToken)
        try rootContainer.encode(tokenType, forKey: .tokenType)
        try rootContainer.encodeIfPresent(refreshToken, forKey: .refreshToken)
        try rootContainer.encode(expiresIn, forKey: .expiresIn)
        try rootContainer.encode(expiresOn.timeIntervalSinceReferenceDate, forKey: .expiresOn)
        try rootContainer.encodeIfPresent(idToken, forKey: .idToken)
        try rootContainer.encodeIfPresent(scope, forKey: .scope)
    }
}

extension TokenInfo: Hashable {
    // Equatable implementation (Required by Hashable)
    public static func == (lhs: TokenInfo, rhs: TokenInfo) -> Bool {
        return lhs.accessToken == rhs.accessToken &&
               lhs.refreshToken == rhs.refreshToken &&
               lhs.expiresIn == rhs.expiresIn &&
               lhs.tokenType == rhs.tokenType &&
               lhs.expiresOn == rhs.expiresOn
    }

    // Hashable implementation
    public func hash(into hasher: inout Hasher) {
        hasher.combine(accessToken)
        hasher.combine(refreshToken)
        hasher.combine(expiresIn)
        hasher.combine(tokenType)
        hasher.combine(expiresOn)
    }
}

extension TokenInfo {
    /// Decodes the token expiration date from supported payload formats.
    ///
    /// Supported formats:
    /// - Apple reference date (seconds since 1 Jan 2001)
    /// - Unix epoch timestamp (seconds since 1 Jan 1970)
    /// - ISO8601 string
    /// - Missing value (calculated from expiresIn)
    ///
    /// Historical payload examples:
    ///
    /// ```json
    /// "expires_on": 803186654.91093802
    /// ```
    ///
    /// ```json
    /// "expires_on": 1672727571.632
    /// ```
    ///
    /// ```json
    /// "expires_on": "2023-01-03T06:32:51.632Z"
    /// ```
    private static func decodeExpiresOn(from container: KeyedDecodingContainer<CodingKeys>, expiresIn: Int) throws -> Date {
        // MARK: Numeric formats

        if let timestamp = try? container.decodeIfPresent(Double.self, forKey: .expiresOn) {
            let referenceDate = Date(timeIntervalSinceReferenceDate: timestamp)
            let unixDate = Date(timeIntervalSince1970: timestamp)

            let now = Date()

            // Reject obviously unreasonable dates.
            let reasonablePast = now.addingTimeInterval(-60 * 60 * 24 * 365 * 10)   // 10 years ago
            let reasonableFuture = now.addingTimeInterval(60 * 60 * 24 * 365 * 10)  // 10 years ahead

            let referenceIsReasonable =
                referenceDate >= reasonablePast &&
                referenceDate <= reasonableFuture

            let unixIsReasonable =
                unixDate >= reasonablePast &&
                unixDate <= reasonableFuture

            switch (referenceIsReasonable, unixIsReasonable) {
            case (true, false):
                return referenceDate

            case (false, true):
                return unixDate

            case (true, true):
                // Prefer Apple Reference Date for compatibility with
                // current persisted format.
                return referenceDate

            default:
                // Neither interpretation looks valid.
                break
            }
        }

        // MARK: ISO8601 string
        if let dateString = try? container.decodeIfPresent(String.self, forKey: .expiresOn) {
            let formatter = ISO8601DateFormatter()

            formatter.formatOptions = [
                .withInternetDateTime,
                .withFractionalSeconds
            ]

            if let date = formatter.date(from: dateString) {
                return date
            }

            formatter.formatOptions = [
                .withInternetDateTime
            ]

            if let date = formatter.date(from: dateString) {
                return date
            }

            throw DecodingError.dataCorruptedError(
                forKey: .expiresOn,
                in: container,
                debugDescription: "Unsupported expires_on format: \(dateString)"
            )
        }

        // MARK: Missing expires_on
        return Date(timeIntervalSinceNow: TimeInterval(expiresIn))
    }
}
