//
// Copyright contributors to the IBM Verify FIDO2 SDK for iOS project
//

import Foundation
import Security
import LocalAuthentication
import CryptoKit
import os.log

/// This class provides helper methods to generate, query and delete private keys.  In addition, the class provides the ability to sign data and export the public key.
internal struct SecKeyStore {
    private let serviceName: String
    private let accessGroup: String?
    
    // The access control to geneate and sign with the private key.
    private let accessControl = SecAccessControlCreateWithFlags(nil,
                                                                kSecAttrAccessibleWhenUnlockedThisDeviceOnly,
                                                                [.privateKeyUsage, .userPresence],
                                                                nil)!
    
    /// Initializes the KeyStore with identifying tags and groups.
    /// - Parameters:
    ///   - applicationTag: A unique string identifying this category of keys.
    ///   - accessGroup: The shared Keychain Group (e.g. "TEAMID.group.com.app"). If nil, uses private keychain.
    init(serviceName: String, accessGroup: String? = nil) {
        // Convert to Data immediately as the Keychain API requires [kSecAttrApplicationTag: Data]
        self.serviceName = serviceName
        self.accessGroup = accessGroup
    }
    
    // MARK: - Helper Methods
        
    /// Constructs the base query used for identifying keys in the keychain.
    internal func query(for account: String) -> [String: Any] {
        var query: [String: Any] = [
            kSecClass as String: kSecClassGenericPassword,
            kSecAttrService as String: serviceName,
            kSecAttrAccount as String: account
        ]
        
        if let accessGroup = accessGroup {
            query[kSecAttrAccessGroup as String] = accessGroup
        }
        
        return query
    }
    
    // MARK: - Key Operations

    /// Generates the private and public key for future signing operations.
    func generate(context: LAContext) throws -> SecureEnclave.P256.Signing.PrivateKey {
        os_log("Generating private key in SecureEnclave.", log: .crypto, type: .info)
        
        // Note: The key in memory first. The 'add' method will persist the reference.
        let key = try SecureEnclave.P256.Signing.PrivateKey(compactRepresentable: true,
                                                            accessControl: self.accessControl,
                                                            authenticationContext: context)
        os_log("Private key created successfully.", log: .crypto, type: .info)
        return key
    }
    
    /// Stores a SecureEnclave key reference in the keychain.
    /// - Parameters:
    ///   - account: The account to store the key under (usually the Credential ID).
    ///   - key: The key generated by the Secure Enclave.
    func add(_ account: String, key: SecureEnclave.P256.Signing.PrivateKey) throws {
        var query = query(for: account)
        
        // Add the data
        query[kSecValueData as String] = key.dataRepresentation // Store the opaque reference
        
        let status = SecItemAdd(query as CFDictionary, nil)
        
        guard status == errSecSuccess else {
            os_log("Unable to store item %{public}@. Status: %{public}@", log: .default, type: .error, account, status.message)
            throw KeyStoreError("Unable to store item. \(status.message)")
        }
        
        os_log("Key %{public}@ added to Keychain.", log: .crypto, type: .info, account)
    }
    
    /// Reads a SecureEnclave key from the keychain.
    /// - Parameters:
    ///   - account: The account assigned to the key.
    ///   - context: The Local Authentication context to associate with the key. Default is nil.
    /// - Returns: The `SecureEnclave.P256.Signing.PrivateKey` if found, otherwise `nil`.
    func read(_ account: String, context: LAContext) -> SecureEnclave.P256.Signing.PrivateKey? {
        var query = query(for: account)
        query[kSecReturnData as String] = true
        
        // Find and cast the result as data.
        var item: CFTypeRef?
        let status = SecItemCopyMatching(query as CFDictionary, &item)
        
        switch status {
        case errSecSuccess:
            if let data = item as? Data {
                os_log("Key found with name %{public}@.", log: .crypto, type: .info, account)
                // Reconstruct the key from the reference data
                return try? SecureEnclave.P256.Signing.PrivateKey(dataRepresentation: data, authenticationContext: context)
            }
            return nil
            
        case errSecItemNotFound:
            os_log("No key found with name %{public}@.", log: .crypto, type: .info, account)
            return nil
            
        default:
            os_log("Keychain read failed for %{public}@. Status: %{public}@", log: .crypto, type: .error, account, status.message)
            return nil
        }
    }
    
    /// Removes any existing key with the given account.
    /// - Parameter account: The account assigned to the key.
    func delete(_ account: String) throws {
        let query = query(for: account)
        
        let status = SecItemDelete(query as CFDictionary)
        
        switch status {
        case errSecItemNotFound, errSecSuccess:
            os_log("Key %{public}@ deleted (or did not exist).", log: .crypto, type: .info, account)
            break // Okay to ignore
        default:
            os_log("Unexpected deletion error for %{public}@. Status: %{public}@", log: .crypto, type: .error, account, status.message)
            throw KeyStoreError("Unexpected deletion error. \(status.message)")
        }
    }
}

/// The error description for a failed `SecKey` operations.
struct KeyStoreError: Error, LocalizedError, CustomStringConvertible {
    private var _description: String
    
    /// Initiatizes a new `KeyStoreError` instance.
    /// - Parameter description: The error messge accompanying the error.
    init(_ description: String) {
        self._description = description
    }
    
    /// The error description accompanying the error.
    public var description: String {
        return _description
    }
    
    public var localizedDescription: String {
        return NSLocalizedString(_description, comment: "")
    }
}

extension OSStatus {
    /// A human readable message for the status.
    var message: String {
        return (SecCopyErrorMessageString(self, nil) as String?) ?? String(self)
    }
}
