//
// Copyright contributors to the IBM Verify MFA SDK for iOS project
//

import Foundation
import Authentication
import Core
import os

/// A type that indicates when the cloud service fails.
public typealias CloudServiceError = MFAServiceError

/// The `CloudAuthenticatorService` enables authenticators to perform transaction, login and token refresh operations.
public actor CloudAuthenticatorService: MFAServiceDescriptor {
    /// The enumerated type to apply to retrieving cloud transaction data.
    internal enum TransactionFilter: String {
        /// Includes id, creationTime, transactionData and authenticationMethods when the transaction is pending.
        ///
        /// Sorted by creation time.
        case nextPending = "?filter=id,creationTime,transactionData,correlationEnabled,correlationValue,expiryTime,authenticationMethods&search=state=%22PENDING%22&sort=-creationTime"

        /// Includes id, creationTime, transactionData and authenticationMethods when the transaction pending.
        ///
        /// Search is by id={transactionId}.
        case pendingByIdentifier = "?filter=id,creationTime,transactionData,correlationEnabled,correlationValue,expiryTime,authenticationMethods&search=state=\u{22}PENDING\u{22}&id=\u{22}%@\u{22}"
    }
    
    private let logger = Logger(subsystem: "com.ibm.security.verifysdk", category: "mfa")

    // MARK: - Properties
    
    public private(set) var accessToken: String
    public private(set) var currentPendingTransaction: PendingTransactionInfo?
    public var publicKeyCertificate: String? = nil
    nonisolated public let refreshUri: URL
    nonisolated public let transactionUri: URL
    
    @_documentation(visibility: private)
    public let _urlSession: URLSession
    
    /// A unique identifier to link a mobile application to the cloud service.
    private let authenticatorId: String
    
    /// Creates the service with the access token and related endpoint URI's.
    /// - Parameters:
    ///   - accessToken: The access token generated by the authorization server.
    ///   - refreshUri: The location of the endpoint to refresh the OAuth token for the authenticator.
    ///   - transactionUri: The location of the endpoint to perform transaction validation.
    ///   - authenticatorId: An identifier generated during registration to uniquely identify the authenticator.
    ///   - certificateTrust: A delegate to handle session-level certificate pinning.
    public init(with accessToken: String, refreshUri: URL, transactionUri: URL, authenticatorId: String, certificateTrust: URLSessionDelegate? = nil) {
        self.accessToken = accessToken
        self.refreshUri = refreshUri
        self.transactionUri = transactionUri
        self.authenticatorId = authenticatorId
        
        // Set the URLSession for certificate pinning with ephemeral configuration to prevent cookie persistence across operations.
        self._urlSession = {
            let configuration = URLSessionConfiguration.ephemeral
            configuration.timeoutIntervalForRequest = 15
            configuration.waitsForConnectivity = false
            return URLSession(configuration: configuration,
                delegate: certificateTrust,
                delegateQueue: nil)
        }()
    }
    
    /// Refresh the OAuth token associated with the registered authenticator.
    ///
    /// The resulting access token is automatically updated in the instance of the `CloudAuthenticatorService` for subsequent operations.
    ///
    /// ```swift
    /// // Using the authenticator properties, create a new CloudAuthenticatorService.
    /// let service = CloudAuthenticatorService(with: authenticator.token.accessToken, refreshUri: authenticator.refreshUri, transactionUri: authenticator.transactionUri)
    ///
    /// // Invoke the refreshToken(autnticator.token.refreshToken) method, optional is the accountName and pushToken.
    /// let result = try await service.refreshToken(using: "abc123")
    /// print(result)
    ///
    /// // Update authenticator token.
    /// authenticator.token = result
    ///
    /// // Encode and save the authenticator to JSON file.
    /// let encoder = JSONEncoder()
    /// encoder.outputFormatting = .prettyPrinted
    /// 
    /// let data = try encoder.encode(authenticator)
    /// print(String(data: data, encoding: .utf8)!)
    /// data.write(to: "authenticator.json")
    /// ```
    ///
    /// - Parameters:
    ///   - refreshToken: The refresh token of the existing authenticator registration.
    ///   - accountName: A list of values added to the initiation request.
    ///   - pushToken: A token that identifies the device to Apple Push Notification Service (APNS).
    ///   - additionalData: (Optional) A collection of options associated with the service.
    /// - Returns: A new `TokenInfo` for the authenticator.
    ///
    /// Communicate with Apple Push Notification service (APNs) and receive a unique device token that identifies your app.  Refer to [Registering Your App with APNs](https://developer.apple.com/documentation/usernotifications/registering_your_app_with_apns).
    public func refreshToken(using refreshToken: String, accountName: String? = nil, pushToken: String? = nil, additionalData: [String: Any]? = nil) async throws -> TokenInfo {
        logger.info("Attempting cloud token refresh for authenticator: \(self.authenticatorId, privacy: .public)")
        
        var attributes = MFAAttributeInfo.dictionary()
        attributes.removeValue(forKey: "applicationName")
        attributes["accountName"] = accountName
        attributes["pushToken"] = pushToken
        
        // Merge any additional data provided by the caller.
        if let additionalData {
            attributes.merge(additionalData) { (_, new) in new }
        }
        
        let data: [String: Any] = [
            "refreshToken": refreshToken,
            "attributes": attributes
        ]
        
        // Convert the body dictionary to Data.
        let body: Data
        do {
            body = try JSONSerialization.data(withJSONObject: data)
        }
        catch {
            logger.error("Failed to serialize refresh request: \(error.localizedDescription, privacy: .public)")
            throw MFAServiceError.dataDecodingFailed(reason: String(localized: "Failed to convert data to JSON.", bundle: .module))
        }
        
        // Construct and perform the network request.
        let resource = HTTPResource<TokenInfo>(json: .post, url: refreshUri, body: body)
        
        do {
            let result = try await self._urlSession.dataTask(for: resource)
            self.accessToken = result.accessToken
            logger.info("Token refresh successful.")
            return result
        }
        catch {
            logger.error("Token refresh failed: \(error.localizedDescription, privacy: .public)")
            throw error
        }
    }
    
    /// Fetches the next pending transaction, optionally filtered by an identifier.
    ///
    /// - Parameter transactionId: An optional ID to fetch a specific transaction.
    /// - Throws: `MFAServiceError` if the URL cannot be constructed.
    /// - Returns: A `NextTransactionInfo` object with the transaction details.
    ///
    /// When a `transactionId` is supplied, information relating to that transaction identifier is returned while in a PENDING state.  Otherwise the next transaction is returned.
    /// ```swift
    /// // Using the authenticator properties, create a new CloudAuthenticatorService.
    /// let service = CloudAuthenticatorService(with: authenticator.token.accessToken, refreshUri: authenticator.refreshUri, transactionUri: authenticator.transactionUri)
    ///
    /// // Invoke the nextTransaction() method, optional is the transacionID.
    /// let result = try await service.nextTransaction()
    /// print(result)
    /// ```
    public func nextTransaction(with transactionId: String? = nil) async throws -> NextTransactionInfo {
        logger.info("Fetching next cloud transaction. Explicit ID: \(transactionId ?? "None", privacy: .public)")
        
        let queryString = transactionId != nil
            ? String(format: TransactionFilter.pendingByIdentifier.rawValue, transactionId!)
            : TransactionFilter.nextPending.rawValue
            
        guard let url = URL(string: "\(self.transactionUri.absoluteString)\(queryString)") else {
            logger.error("Failed to construct URL for cloud transaction fetch.")
            return NextTransactionInfo(current: nil, countOfPendingTransactions: 0)
        }
        
        let headers = ["Authorization": "Bearer \(self.accessToken)"]
        let resource = HTTPResource<NextTransactionInfo>(.get, url: url, accept: .json, headers: headers, parse: parsePendingTransaction)
        
        do {
            let result = try await self._urlSession.dataTask(for: resource)
            self.currentPendingTransaction = result.current
            return result
        }
        catch {
            logger.error("Error fetching cloud transactions: \(error.localizedDescription, privacy: .public)")
            return NextTransactionInfo(current: nil, countOfPendingTransactions: 0)
        }
    }
    
    public func completeTransaction(action userAction: UserAction = .verify, signedData: String) async throws {
        guard let pendingTransaction = currentPendingTransaction else {
            logger.error("Attempted to complete cloud transaction, but no transaction is currently pending.")
            throw MFAServiceError.invalidPendingTransaction
        }
        
        defer { self.currentPendingTransaction = nil }
        
        try await completeTransaction(transaction: pendingTransaction, action: userAction, signedData: signedData)
    }
    
    public func completeTransaction(transaction pendingTransaction: PendingTransactionInfo, action userAction: UserAction, signedData: String) async throws {
        logger.info("Completing cloud transaction \(pendingTransaction.id, privacy: .public) with action: \(userAction.rawValue, privacy: .public)")
                
        let data: [[String: Any]] = userAction == .verify
            ? [["id": pendingTransaction.factorId.lowercased(), "userAction": userAction.rawValue, "signedData": signedData]]
            : [["id": pendingTransaction.factorId.lowercased(), "userAction": userAction.rawValue]]
        
        guard let body = try? JSONSerialization.data(withJSONObject: data, options: []) else {
            throw MFAServiceError.dataDecodingFailed(reason: String(localized: "Unable to encode JSON request.", bundle: .module))
        }
        
        let headers = ["Authorization": "Bearer \(self.accessToken)"]
        let resource = HTTPResource<Void>(.post, url: pendingTransaction.postbackUri, accept: .json, contentType: .json, body: body, headers: headers)
        
        do {
            try await self._urlSession.dataTask(for: resource)
            logger.info("Successfully posted cloud transaction response.")
        }
        catch {
            logger.error("Failed to complete cloud transaction '\(userAction.rawValue)': \(error.localizedDescription, privacy: .public)")
            throw error
        }
    }
}

extension CloudAuthenticatorService {
    // MARK: Internal transaction structures
    
    /// Describes the result of acquiring a pending transction from cloud instances.
    internal struct TransactionResult: Decodable {
        var count: Int = 0
        var verifications: [VerificationInfo]?

        /// The root level JSON structure for decoding.
        private enum CodingKeys: String, CodingKey {
            case total
            case verifications
        }

        struct VerificationInfo: Decodable {
            let id: String
            let creationTime: Date
            let expiryTime: Date
            let correlationEnabled: Bool
            var correlationValue: String?
            let transactionInfo: String
            let methodInfo: [MethodInfo]

            /// The nested root decoding structure based off `CodingKeys`.  Used for cloud transaction data and method parsing.
            private enum CodingKeys: String, CodingKey {
                case id
                case creationTime
                case expiryTime
                case correlationEnabled
                case correlationValue
                case transactionInfo = "transactionData"
                case methodInfo = "authenticationMethods"
            }
        }

        struct MethodInfo: Decodable {
            let id: String
            let methodType: String
            let subType: String
            let additionalData: [AdditionalDataItem]
            
            var keyName: String? {
                additionalData.first(where: { $0.name == "name" })?.value
            }
            
            struct AdditionalDataItem: Decodable {
                let name: String
                let value: String
            }
        }

        // MARK: Initializers

        /// Creates a new instance by decoding from the given decoder.
        /// - Parameter decoder: The decoder to read data from.
        public init(from decoder: Decoder) throws {
            // Root keys
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)
            count = try rootContainer.decode(Int.self, forKey: .total)
            verifications = try rootContainer.decode([VerificationInfo].self, forKey: .verifications)
        }
    }
}

extension CloudAuthenticatorService {
    /// Parse the pending transaction for a cloud authenticator.
    ///
    /// - Parameters:
    ///   - data: The data returned by the server.
    ///   - response: An object that provides response metadata, such as HTTP headers and status code.
    /// - Returns: A value that represents either a success or a failure, including an associated value in each case.
    private func parsePendingTransaction(data: Data?, response: URLResponse?) -> Result<NextTransactionInfo, Error> {
        guard let data = data, !data.isEmpty else {
            logger.warning("Empty response received from cloud transaction endpoint.")
            return .success(NextTransactionInfo(current: nil, countOfPendingTransactions: 0))
        }
        
        let decodedResult: TransactionResult
        
        do {
            let decoder = JSONDecoder()
            decoder.dateDecodingStrategy = .formatted(DateFormatter.iso8601FormatterBehavior)
            decodedResult = try decoder.decode(TransactionResult.self, from: data)
        }
        catch {
            logger.error("Failed to decode cloud transaction JSON: \(error.localizedDescription, privacy: .public)")
            return .failure(MFAServiceError.dataDecodingFailed(reason: error.localizedDescription))
        }

        guard decodedResult.count > 0 else {
            return .success(NextTransactionInfo(current: nil, countOfPendingTransactions: 0))
        }
        
        if let pendingTransaction = createPendingTransaction(using: decodedResult) {
            return .success(NextTransactionInfo(current: pendingTransaction, countOfPendingTransactions: decodedResult.count))
        }
        
        return .failure(MFAServiceError.dataDecodingFailed(reason: String(localized: "Unable to find valid transaction in response.", bundle: .module)))
    }
    
    /// Creates a `PendingTransaction` based on the parsed transaction and attribute data.
    ///
    /// - Parameters:
    ///    - result: The `CloudTransactionResult` containing the parsed data.
    /// - Throws: `MFAServiceError` if required data is missing.
    /// - Returns: A `PendingTransactionInfo` object.
    private func createPendingTransaction(using result: TransactionResult) -> PendingTransactionInfo? {
        // 1. Get the first transaction and related method.
        guard let verificationInfo = result.verifications?.first, let methodInfo = verificationInfo.methodInfo.first else {
            return nil
        }

        // 2. Get the postback to the transaction.
        let postbackUri = self.transactionUri.appendingPathComponent(verificationInfo.id)

        // 3. Get the message to display.
        let message = transactionMessage(using: verificationInfo.transactionInfo)
        // 4. Construct the transaction context information into additional data.
        let additionalData = createAdditionalData(using: verificationInfo)
        
        // 5. The keyName in v3 is derived from signature additonalData, if it doesn't exist (i.e v2 enrolment), construct it.
        let keyName = methodInfo.keyName
            ?? "\(authenticatorId).\(methodInfo.subType == "userPresence" ? "userPresence" : "biometrics")"

        // 6. Construct the pending transaction taking data from the transaction, attribute and authentication info.
        let pendingTransactionInfo = PendingTransactionInfo(
            id: verificationInfo.id,
            message: message,
            postbackUri: postbackUri,
            keyName: keyName,
            factorId: methodInfo.id,
            factorType: methodInfo.subType,
            dataToSign: verificationInfo.transactionInfo,
            timeStamp: verificationInfo.creationTime,
            expiryTime: verificationInfo.expiryTime,
            additionalData: additionalData
        )

        return pendingTransactionInfo
    }

    /// Creates a dictionary of available transaction data from the `CloudTransactionResult`.
    /// - Parameters:
    ///   - info: The `VerificationInfo` containing the additional transaction data..
    /// - Returns: An array of `TransactionAttribute` and corresponding value.
    private func createAdditionalData(using info: TransactionResult.VerificationInfo) -> [TransactionAttribute: String] {
        var result: [TransactionAttribute: String] = [:]

        // Convert the String into Data and serialize to JSON object.
        guard let jsonData = info.transactionInfo.data(using: .utf8), var data = try? JSONSerialization.jsonObject(with: jsonData, options: []) as? [String: Any] else {
            return result
        }
        
        // Add the IP address to the result, then remove from dictionary.
        if let ipAddress = data["originIpAddress"] as? String {
            result[.ipAddress] = ipAddress
            data.removeValue(forKey: "originIpAddress")
        }

        // Add the user-agent to the result, then remove from dictionary.
        if let userAgent = data["originUserAgent"] as? String {
            result[.userAgent] = userAgent
            data.removeValue(forKey: "originUserAgent")
        }

        // Calculate the correlation value if requried, adding to additionalData.
        if info.correlationEnabled {
            if let correlationValue = info.correlationValue {
                result.updateValue(correlationValue, forKey: .correlation)
            }
            else {
                // Take for the first 32-bits of the transactionId, then mod 100 to generate a 2 digit value.
                let correlationValue = computeCorrelationValue(from: info.id)
                
                 result.updateValue(correlationValue, forKey: .correlation)
            }
        }
        
        // Add the default type (of request) to the result.  Might be overriden if specified in additionalData.
        result[.type] = String(localized: "Request", bundle: .module)

        // Process the additional data array.
        if let additionalData = data["additionalData"] as? [[String: String]] {
            var customData: [[String: String]] = []
            for item in additionalData {
                guard let name = item["name"], let value = item["value"] else {
                    continue
                }
               
                switch name {
                case "type":
                   result[.type] = value
                case "originLocation":
                    result[.location] = value
                case "imageURL":
                    result[.image] = value
                default:
                    customData.append(item)
                }
           }

            // Assign remaining values to TransactionAttribute.custom.
            if !customData.isEmpty, let customJsonData = try? JSONSerialization.data(withJSONObject: customData) {
                let customJsonString = String(data: customJsonData, encoding: .utf8)
                result[.custom] = customJsonString
            }
        }

        return result
    }

    /// Gets the message associated with the transaction data from the `TransactionResult`.
    /// - Parameters:
    ///   - value: A JSON string representing the transaction data `VerificationInfo`.
    /// - Returns: The transaction message or the default pending transaction message.
    private func transactionMessage(using value: String) -> String {
        guard let jsonData = value.data(using: .utf8), let data = try? JSONSerialization.jsonObject(with: jsonData, options: []) as? [String: Any], let message = data["message"] as? String else {
            return String(localized: "You have a pending request.", bundle: .module)
        }
                
        return message
    }
}
