//
// Copyright contributors to the IBM Verify MFA SDK for iOS project
//

import Foundation
import Authentication
import Core
import SwiftUI
import os


/// A service responsible for managing on-premise multi-factor authentication operations.
///
/// `OnPremiseAuthenticatorService` handles token lifecycle, retrieving pending verification transactions,
/// and submitting user responses (verify, deny, fraud) back to the server.
public actor OnPremiseAuthenticatorService: MFAServiceDescriptor {
    private let logger = Logger(subsystem: "com.ibm.security.verifysdk", category: "mfa")

    // MARK: - Properties
    
    @_documentation(visibility: private)
    public let _urlSession: URLSession
    
    public private(set) var accessToken: String
    public private(set) var currentPendingTransaction: PendingTransactionInfo?
    nonisolated public let refreshUri: URL
    nonisolated public let transactionUri: URL

    /// The unique identifier between the service and the client app.
    private let clientId: String

    /// A unique identifier linking the mobile application to the on-premise service.
    private let authenticatorId: String

    // MARK: - Initialization

    /// Creates the service with the access token and related endpoint URIs.
    /// - Parameters:
    ///   - accessToken: The access token generated by the authorization server.
    ///   - refreshUri: The location of the endpoint to refresh the OAuth token.
    ///   - transactionUri: The location of the endpoint to query and validate transactions.
    ///   - clientId: The unique identifier between the service and the client app.
    ///   - authenticatorId: An identifier generated during registration to uniquely identify the authenticator.
    ///   - certificateTrust: An optional delegate to handle session-level certificate pinning.
    public init(with accessToken: String, refreshUri: URL, transactionUri: URL, clientId: String, authenticatorId: String, certificateTrust: URLSessionDelegate? = nil) {
        self.accessToken = accessToken
        self.refreshUri = refreshUri
        self.transactionUri = transactionUri
        self.clientId = clientId
        self.authenticatorId = authenticatorId

        // Ephemeral configuration prevents cookie persistence across MFA operations.
        self._urlSession = {
            let configuration = URLSessionConfiguration.ephemeral
            configuration.timeoutIntervalForRequest = 15
            configuration.waitsForConnectivity = false
            return URLSession(configuration: configuration,
                              delegate: certificateTrust,
                              delegateQueue: nil)
        }()
    }

    // MARK: Parameter Helpers
    
    /// Creates a dictionary of additional parameters for OAuth requests.
    /// - Parameters:
    ///   - accountName: The account name to include (optional).
    ///   - pushToken: The push token to include (optional).
    ///   - tenantId: The tenant ID to include.
    ///   - additionalData: Optional additional data to merge (up to 10 items).
    /// - Returns: A dictionary with the combined parameters.
    nonisolated public static func createAdditionalParameters(accountName: String? = nil, pushToken: String? = nil, tenantId: String, additionalData: [String: Any]? = nil) -> [String: Any] {
        var parameters = MFAAttributeInfo.dictionary(snakeCaseKey: true)
        parameters["accountName"] = accountName
        parameters["pushToken"] = pushToken
        parameters["tenant_id"] = tenantId

        // If there is additional data, merge with the parameters retaining existing values and only adding 10 additional parameters
        if let additionalData {
            for (key, value) in additionalData.prefix(10) where parameters[key] == nil {
                parameters[key] = value
            }
        }

        return parameters
    }
    
    // MARK: - Public Service API

    public func refreshToken(using refreshToken: String, accountName: String? = nil, pushToken: String? = nil, additionalData: [String: Any]? = nil) async throws -> TokenInfo {
        logger.info("Attempting OAuth token refresh for authenticator: \(self.authenticatorId, privacy: .public)")
        
        let attributes = OnPremiseAuthenticatorService.createAdditionalParameters(
            accountName: accountName,
            pushToken: pushToken,
            tenantId: self.authenticatorId,
            additionalData: additionalData
        )

        let oauthProvider = OAuthProvider(clientId: clientId, additionalParameters: attributes, certificateTrust: self._urlSession.delegate)
        
        do {
            let result = try await oauthProvider.refresh(issuer: self.refreshUri, refreshToken: refreshToken)
            self.accessToken = result.accessToken
            logger.info("Token refresh successful.")
            return result
        }
        catch {
            logger.error("Token refresh failed: \(error.localizedDescription, privacy: .public)")
            throw error
        }
    }

    public func nextTransaction(with transactionId: String? = nil) async throws -> NextTransactionInfo {
        logger.info("Fetching next transaction. Explicit ID: \(transactionId ?? "None", privacy: .public)")
        
        let decoder = JSONDecoder()
        decoder.dateDecodingStrategy = .formatted(DateFormatter.iso8601FormatterBehavior)

        let headers = ["Authorization": "Bearer \(self.accessToken)"]
        let resource = HTTPResource<TransactionResult>(json: .get, url: transactionUri, accept: .json, headers: headers, decoder: decoder)

        let transactionResult: TransactionResult
        do {
            transactionResult = try await self._urlSession.dataTask(for: resource)
        }
        catch {
            logger.error("Network or decoding failure during transaction fetch: \(String(describing: error), privacy: .public)")
            return NextTransactionInfo(current: nil, countOfPendingTransactions: 0)
        }

        if transactionResult.transactions.isEmpty {
            logger.info("No pending transactions found.")
            return NextTransactionInfo(current: nil, countOfPendingTransactions: 0)
        }

        let availableTransactions: [TransactionResult.TransactionInfo]
        
        if let transactionId {
            availableTransactions = transactionResult.transactions.filter { $0.transactionId == transactionId }
        }
        else {
            let attributes = transactionResult.attributes
                .filter { $0.uri == "mmfa:request:authenticator:id" && $0.values.contains(authenticatorId) }
                .map { $0.transactionId }
            
            availableTransactions = transactionResult.transactions
                .filter { attributes.contains($0.transactionId) }
                .sorted { $0.creationTime < $1.creationTime }
        }

        // Evaluate sequentially and stop at the first successfully built transaction
        for transaction in availableTransactions {
            do {
                let relevantAttributes = transactionResult.attributes.filter { $0.transactionId == transaction.transactionId }
                let pendingTransaction = try await createPendingTransaction(info: transaction, attributes: relevantAttributes)
                
                self.currentPendingTransaction = pendingTransaction
                logger.info("Successfully prepared transaction: \(transaction.transactionId, privacy: .public)")
                return NextTransactionInfo(current: pendingTransaction, countOfPendingTransactions: transactionResult.transactions.count)
                
            }
            catch {
                logger.error("Failed to process transaction \(transaction.transactionId, privacy: .public), skipping. Reason: \(String(describing: error), privacy: .public)")
                continue
            }
        }

        self.currentPendingTransaction = nil
        return NextTransactionInfo(current: nil, countOfPendingTransactions: transactionResult.transactions.count)
    }

    /// Completes the currently active pending transaction.
    /// - Parameters:
    ///   - userAction: The action the user took (`verify`, `deny`, `markAsFraud`). Defaults to `.verify`.
    ///   - signedData: The cryptographic signature verifying the user's consent.
    public func completeTransaction(action userAction: UserAction = .verify, signedData: String) async throws {
        guard let pendingTransaction = currentPendingTransaction else {
            logger.error("Attempted to complete transaction, but no transaction is currently pending.")
            throw MFAServiceError.invalidPendingTransaction
        }

        defer {
            self.currentPendingTransaction = nil
        }

        try await completeTransaction(transaction: pendingTransaction, action: userAction, signedData: signedData)
    }

    public func completeTransaction(transaction pendingTransaction: PendingTransactionInfo, action userAction: UserAction, signedData: String) async throws {
        logger.info("Completing transaction \(pendingTransaction.id, privacy: .public) with action: \(userAction.rawValue, privacy: .public)")
        
        let data: [String: Any] = [
            "signedChallenge": userAction == .verify ? signedData : "",
            "userAction": userAction.rawValue
        ]

        let body = try JSONSerialization.data(withJSONObject: data, options: [])
        let headers = ["Authorization": "Bearer \(self.accessToken)"]
        let resource = HTTPResource<Void>(.put, url: pendingTransaction.postbackUri, accept: .json, contentType: .json, body: body, headers: headers)

        do {
            try await self._urlSession.dataTask(for: resource)
            logger.info("Successfully posted transaction response.")
        }
        catch {
            // If the request is a user deny, no error should be returned.
            if userAction == .deny || userAction == .markAsFraud {
                return
            }
            else {
                // Reverted: Log the error and allow it to propagate to the caller.
                logger.error("Failed to complete transaction '\(userAction.rawValue)': \(error.localizedDescription, privacy: .public)")
                throw error
            }
        }
    }

    /// Removes the authenticator registration from the server.
    ///
    /// See [AuthenticationPostTokenGeneration](https://www.ibm.com/docs/en/sva/10.0.1?topic=rules-mmfa-mapping-rule-methods)
    ///
    /// ```swift
    /// if let identifier = authenticator.token.additionalData["authenticator_id"] {
    ///   let service = OnPremiseAuthenticatorService(with: authenticator.token.accessToken,
    ///                             refreshUri: authenticator.refreshUri,
    ///                             transactionUri: authenticator.transactionUri,
    ///                             clientId: authenticator.clientId,
    ///                             authenticatorId: authenticator.id)
    ///
    ///  // Attempt to remove the registered authenticator.
    ///  try await service.remove()
    /// }
    /// ```
    public func remove() async throws {
        logger.info("Initiating unregistration for authenticator: \(self.authenticatorId, privacy: .public)")
        
        let data: [String: Any] = [
            "schemas": ["urn:ietf:params:scim:api:messages:2.0:PatchOp"],
            "Operations": [
                [
                    "op": "remove",
                    "path": "urn:ietf:params:scim:schemas:extension:isam:1.0:MMFA:Authenticator:authenticators[id eq \(self.authenticatorId)]"
                ]
            ]
        ]

        let body = try JSONSerialization.data(withJSONObject: data, options: [])
        let headers = ["Authorization": "Bearer \(self.accessToken)"]

        // Use the transactionUri to derived the unregister location.
        var componentsUri = URLComponents(url: transactionUri, resolvingAgainstBaseURL: false)!

        // Update the query string to reduce the response body returned.
        componentsUri.query = "attributes=urn:ietf:params:scim:schemas:extension:isam:1.0:MMFA:Authenticator:authenticators"
        let url = componentsUri.url!

        let resource = HTTPResource<Void>(.patch, url: url, accept: .json, contentType: .json, body: body, headers: headers)

        do {
            try await self._urlSession.dataTask(for: resource)
            logger.info("Authenticator successfully removed.")
        }
        catch {
            logger.error("Failed to remove authenticator: \(error.localizedDescription, privacy: .public)")
            throw error
        }
    }
}

// MARK: - Internal Transaction Processing

extension OnPremiseAuthenticatorService {
    // MARK: Internal transaction structures

    /// Describes the result of parsing a pending transction from on-premise instances into transaction and transaction attribute data.
    internal struct TransactionResult: Decodable {
        var transactions: [TransactionInfo] = []
        var attributes: [AttributeInfo] = []

        // MARK: Internal enum

        /// The root level JSON structure for decoding.
        private enum CodingKeys: String, CodingKey {
            case transaction = "urn:ietf:params:scim:schemas:extension:isam:1.0:MMFA:Transaction" // Root JSON from on-premise transaction
        }

        /// The nested root decoding structure based off `CodingKeys`.  Used for on-premise transaction and attribute parsing.
        private enum TransactionCodingKeys: String, CodingKey {
            case transactions = "transactionsPending"
            case attributes = "attributesPending"
        }

        // MARK: Internal structs

        struct AttributeInfo: Codable {
            let dataType: String
            let values: [String]
            let uri: String
            let transactionId: String
        }

        struct TransactionInfo: Codable {
            let creationTime: Date
            let requestUrl: URL
            let transactionId: String
            let authnPolicyUri: String

            var expiryTime: Date {
                creationTime.addingTimeInterval(300)
            }

            /// The nested pending transactions decoding structure based off `OnPremisePendingCodingKeys`.  Used for on-premise transaction parsing.
            private enum CodingKeys: String, CodingKey {
                case creationTime
                case requestUrl
                case transactionId
                case authnPolicyUri = "authnPolicyURI"
            }
        }

        // MARK: Initializeras

        /// Creates a new instance by decoding from the given decoder
        /// - parameter decoder: The decoder to read data from.
        public init(from decoder: Decoder) throws {
            // Root keys
            let rootContainer = try decoder.container(keyedBy: CodingKeys.self)

            // Check if the on-premise root container is present.
            if rootContainer.contains(.transaction) {
                let transactionContainer = try rootContainer.nestedContainer(keyedBy: TransactionCodingKeys.self, forKey: .transaction)
                self.attributes = try transactionContainer.decode([AttributeInfo].self, forKey: .attributes)
                self.transactions = try transactionContainer.decode([TransactionInfo].self, forKey: .transactions)

                // Sort if there are more than one transaction
                if (self.transactions.count) > 1 {
                    self.transactions = self.transactions.sorted(by: { $0.creationTime.compare($1.creationTime) == .orderedDescending })
                }
            }
        }
    }

    /// The verification information to determine how the transaction challenge can be processed.
    private struct VerificationInfo: Decodable {
        let mechanism: String
        let location: String
        let type: String
        var serverChallenge: String
        let keyHandles: [String]
    }

    // MARK: Transaction Builder

    /// Transforms raw transaction information and its strictly associated attributes into a fully populated `PendingTransactionInfo`.
    /// - Parameters:
    ///   - transactionInfo: The parsed transaction header data.
    ///   - attributes: An array of attributes pre-filtered to guarantee they belong to this specific `transactionId`.
    /// - Returns: A complete `PendingTransactionInfo` object ready for UI presentation and cryptographic signing.
    private func createPendingTransaction(info transactionInfo: TransactionResult.TransactionInfo, attributes: [TransactionResult.AttributeInfo]) async throws -> PendingTransactionInfo {
        
        let headers = ["Authorization": "Bearer \(self.accessToken)"]
        let resource = HTTPResource<VerificationInfo>(json: .post, url: transactionInfo.requestUrl, accept: .json, headers: headers)

        let verificationInfo: VerificationInfo
        
        do {
            verificationInfo = try await self._urlSession.dataTask(for: resource)
        }
        catch let urlError as URLError {
            throw MFAServiceError.underlyingError(error: urlError)
        }
        catch {
            throw MFAServiceError.dataDecodingFailed(reason: String(localized: "Unable to decode JSON from transaction response. Detail: \(String(describing: error))", bundle: .module))
        }

        var dataToSign = verificationInfo.serverChallenge

        // Arrays are safely pre-filtered by nextTransaction, so we extract signing metadata directly
        if let signingInfo = attributes.first(where: { $0.uri == "mmfa:request:signing:attributes" }), let value = signingInfo.values.first {
            dataToSign = value
        }

        guard let rawKeyName = verificationInfo.keyHandles.first else {
            throw MFAServiceError.invalidFactor
        }

        // Migrate legacy fingerprint descriptors
        let keyName = rawKeyName.hasSuffix(".fingerprint")
            ? String(rawKeyName.dropLast("fingerprint".count)) + "biometrics"
            : rawKeyName

        let attributeInfo = attributes.filter({ $0.uri == "mmfa:request:context:message" || $0.uri == "mmfa:request:extras" })

        var verificationMessage = NSLocalizedString("You have a pending request", bundle: Bundle.module, comment: "")
        if let messageAttribute = attributeInfo.first(where: { $0.uri == "mmfa:request:context:message" }), let message = messageAttribute.values.first {
            verificationMessage = message
        }

        let postbackUri = createPostbackUrl(using: transactionInfo.requestUrl, path: verificationInfo.location)
        let additionalData = createAdditionalData(with: attributeInfo)

        return PendingTransactionInfo(
            id: transactionInfo.transactionId,
            message: verificationMessage,
            postbackUri: postbackUri,
            keyName: keyName,
            factorId: transactionInfo.authnPolicyUri,
            factorType: verificationInfo.type,
            dataToSign: dataToSign,
            timeStamp: transactionInfo.creationTime,
            expiryTime: transactionInfo.expiryTime,
            additionalData: additionalData)
    }

    /// Creates ``URL`` for a transaction verification to postback to.
    /// - parameter url: An instance of the `URL` object.
    /// - parameter path: The path to append to the URL.
    /// - returns: The unwrapped `URL`.
    private func createPostbackUrl(using url: URL, path: String) -> URL {
        var component = URLComponents()
        component.scheme = url.scheme
        component.host = url.host
        component.port = url.port
        component.path = path

        if let value = component.url?.absoluteString.removingPercentEncoding {
            return URL(string: value)!
        }
        return component.url!
    }

    /// Creates a dictionary of available transaction attributes from the `TransactionResult`.
    /// - parameter attributes: An array of `TransactionResult.AttributeInfo`.
    /// - returns: An array of `TransactionAttribute` and corresponding value.
    private func createAdditionalData(with attributes: [TransactionResult.AttributeInfo]) -> [TransactionAttribute: String] {
        var result: [TransactionAttribute: String] = [:]

        // Check if the extras exist.
        guard let item = attributes.first(where: { $0.uri == "mmfa:request:extras" }) else {
            // If there is no type in the array, add the default "request"
            result.updateValue(NSLocalizedString("PendingRequestTypeDefault", bundle: Bundle.module, comment: ""), forKey: .type)
            return result
        }

        // Process each JSON value in the extras
        for json in item.values {
            // Normalize JSON string: replace single quotes with double quotes for valid JSON
            let normalizedJson = json.replacingOccurrences(of: "'", with: "\"")

            // Safely convert string to data
            guard let value = normalizedJson.data(using: .utf8) else {
                continue // Skip invalid UTF-8 strings
            }

            // Safely parse JSON
            guard let data = try? JSONSerialization.jsonObject(with: value, options: []) as? [String: Any] else {
                continue // Skip invalid JSON or non-dictionary structures
            }

            var mutableData = data

            // Add the type to the result, then remove from dictionary.
            if let type = mutableData["type"] as? String {
                result.updateValue(type, forKey: .type)
                mutableData.removeValue(forKey: "type")
            }

            // Add the IP address to the result, then remove from dictionary.
            if let ipAddress = mutableData["originIpAddress"] as? String {
                result.updateValue(ipAddress, forKey: .ipAddress)
                mutableData.removeValue(forKey: "originIpAddress")
            }

            // Add the user-agent to the result, then remove from dictionary.
            if let userAgent = mutableData["originUserAgent"] as? String {
                result.updateValue(userAgent, forKey: .userAgent)
                mutableData.removeValue(forKey: "originUserAgent")
            }

            // Add the location name to the result, then remove from dictionary.
            if let location = mutableData["originLocation"] as? String {
                result.updateValue(location, forKey: .location)
                mutableData.removeValue(forKey: "originLocation")
            }

            // Add the image to the result, then remove from dictionary.
            if let imageUrl = mutableData["imageURL"] as? String {
                result.updateValue(imageUrl, forKey: .image)
                mutableData.removeValue(forKey: "imageURL")
            }

            // Add the correlation to the result, then remove from dictionary.
            if let value = mutableData["correlationEnabled"] {
                var isEnabled = false

                if let boolValue = value as? Bool {
                    isEnabled = boolValue
                }
                else if let stringValue = value as? String, let boolFromString = Bool(stringValue.lowercased()) {
                    isEnabled = boolFromString
                }

                if isEnabled {
                    if let correlationValue = mutableData["correlationValue"] as? String {
                        result.updateValue("\(correlationValue)", forKey: .correlation)
                        mutableData.removeValue(forKey: "correlationValue")
                    }
                    else {
                        let correlationValue = computeCorrelationValue(from: item.transactionId)
                        result.updateValue("\(correlationValue)", forKey: .correlation)
                    }
                }

                mutableData.removeValue(forKey: "correlationEnabled")
            }

            // Assign the remaining values to TransactionAttribute.custom
            if !mutableData.isEmpty {
                // Normalize the array of values for consistency with Cloud (CIV).  i.e [{"name":"name1", "value": "value1"}, ...]
                var additionalData = [[String: Any]]()

                mutableData.forEach { key, value in
                    additionalData.append(["name": key, "value": value])
                }

                if let customData = try? JSONSerialization.data(withJSONObject: additionalData),
                   let customJson = String(data: customData, encoding: .utf8) {
                    result.updateValue(customJson, forKey: .custom)
                }
            }
        }

        // If there is no type in the array, add the default "request"
        if result.index(forKey: .type) == nil {
            result.updateValue(NSLocalizedString("PendingRequestTypeDefault", bundle: Bundle.module, comment: ""), forKey: .type)
        }

        return result
    }
}
